exec: /
	@echo 'test'
uniqueu: unique.c unsorted.c	
	gcc -o uniqueu unique.c unsorted.c
	time ./uniqueu /scratch/coen12/books/Bible.txt
	time ./uniqueu /scratch/coen12/books/Genesis.txt
	time ./uniqueu /scratch/coen12/books/GreenEggsAndHam.txt
	time ./uniqueu /scratch/coen12/books/HoundOfTheBaskervilles.txt
	time ./uniqueu /scratch/coen12/books/Macbeth.txt
	time ./uniqueu /scratch/coen12/books/TheCountOfMonteCristo.txt
	time ./uniqueu /scratch/coen12/books/TheSecretGarden.txt
	time ./uniqueu /scratch/coen12/books/TheWarOfTheWorlds.txt
	time ./uniqueu /scratch/coen12/books/TreasureIsland.txt
	time ./uniqueu /scratch/coen12/books/TwentyThousandLeagues.txt

uniques: unique.c sorted.c
	gcc -o uniques unique.c sorted.c
	time ./uniques /scratch/coen12/books/Bible.txt
	time ./uniques /scratch/coen12/books/Genesis.txt
	time ./uniques /scratch/coen12/books/GreenEggsAndHam.txt
	time ./uniques /scratch/coen12/books/HoundOfTheBaskervilles.txt
	time ./uniques /scratch/coen12/books/Macbeth.txt
	time ./uniques /scratch/coen12/books/TheCountOfMonteCristo.txt
	time ./uniques /scratch/coen12/books/TheSecretGarden.txt
	time ./uniques /scratch/coen12/books/TheWarOfTheWorlds.txt
	time ./uniques /scratch/coen12/books/TreasureIsland.txt
	time ./uniques /scratch/coen12/books/TwentyThousandLeagues.txt

bincountu: bincount.c unsorted.c
	gcc -o bincountu bincount.c unsorted.c 
	time ./bincountu /scratch/coen12/books/Bible.txt
	time ./bincountu /scratch/coen12/books/Genesis.txt
	time ./bincountu /scratch/coen12/books/GreenEggsAndHam.txt
	time ./bincountu /scratch/coen12/books/HoundOfTheBaskervilles.txt
	time ./bincountu /scratch/coen12/books/Macbeth.txt
	time ./bincountu /scratch/coen12/books/TheCountOfMonteCristo.txt
	time ./bincountu /scratch/coen12/books/TheSecretGarden.txt
	time ./bincountu /scratch/coen12/books/TheWarOfTheWorlds.txt
	time ./bincountu /scratch/coen12/books/TreasureIsland.txt
	time ./bincountu /scratch/coen12/books/TwentyThousandLeagues.txt

bincounts: bincount.c sorted.c
	gcc -o bincounts bincount.c sorted.c 
	time ./bincounts /scratch/coen12/books/Bible.txt
	time ./bincounts /scratch/coen12/books/Genesis.txt
	time ./bincounts /scratch/coen12/books/GreenEggsAndHam.txt
	time ./bincounts /scratch/coen12/books/HoundOfTheBaskervilles.txt
	time ./bincounts /scratch/coen12/books/Macbeth.txt
	time ./bincounts /scratch/coen12/books/TheCountOfMonteCristo.txt
	time ./bincounts /scratch/coen12/books/TheSecretGarden.txt
	time ./bincounts /scratch/coen12/books/TheWarOfTheWorlds.txt
	time ./bincounts /scratch/coen12/books/TreasureIsland.txt
	time ./bincounts /scratch/coen12/books/TwentyThousandLeagues.txt

parityu: parity.c unsorted.c
	gcc -o parityu parity.c unsorted.c 
	time ./parityu /scratch/coen12/books/Bible.txt
	time ./parityu /scratch/coen12/books/Genesis.txt
	time ./parityu /scratch/coen12/books/GreenEggsAndHam.txt
	time ./parityu /scratch/coen12/books/HoundOfTheBaskervilles.txt
	time ./parityu /scratch/coen12/books/Macbeth.txt
	time ./parityu /scratch/coen12/books/TheCountOfMonteCristo.txt
	time ./parityu /scratch/coen12/books/TheSecretGarden.txt
	time ./parityu /scratch/coen12/books/TheWarOfTheWorlds.txt
	time ./parityu /scratch/coen12/books/TreasureIsland.txt
	time ./parityu /scratch/coen12/books/TwentyThousandLeague.txt
 
paritys: parity.c sorted.c
	gcc -o paritys parity.c sorted.c 
	time ./paritys /scratch/coen12/books/Bible.txt
	time ./paritys /scratch/coen12/books/Genesis.txt
	time ./paritys /scratch/coen12/books/GreenEggsAndHam.txt
	time ./paritys /scratch/coen12/books/HoundOfTheBaskervilles.txt
	time ./paritys /scratch/coen12/books/Macbeth.txt
	time ./paritys /scratch/coen12/books/TheCountOfMonteCristo.txt
	time ./paritys /scratch/coen12/books/TheSecretGarden.txt
	time ./paritys /scratch/coen12/books/TheWarOfTheWorlds.txt
	time ./paritys /scratch/coen12/books/TreasureIsland.txt
	time ./paritys /scratch/coen12/books/TwentyThousandLeagues.txt 